### ISSUE TITLE
Make it possible to use docker-compose

### ISSUE THREAD

**Issue by jexp** [jupyter/tmpnb#230]
Then a notebook and dependent containers (e.g. databases) could be started and stopped together. 

Also the container linking would allow easy access from the notebook to the used services.

**Comment by nvenayak** [comment]
You can try something like this:

```
httpproxy:
  image: jupyter/configurable-http-proxy
  environment:
    TOKEN: <random token here>
  container-name:  tmpnb-proxy
  net: "host"
  command:
    default-target: http://127.0.0.1:9999
  ports:
    - 8000:8000


tmpnb_orchestrate:
  image: jupyter/tmpnb
  net: "host"
  container_name: tmpnb_orchestrate
  environment:
    TOKEN: <random token here>
  volumes:
    - /var/run/docker.sock:/docker.sock
```
